import { FormEvent, useEffect, useMemo, useState } from "react";
import { AlertTriangle, Cloud, Code2, Database, ExternalLink, FileText, Home, LogIn, LogOut, Phone, RefreshCw, ShieldCheck, Store, Users, Megaphone, MapPin, Search, TableProperties, CreditCard } from "lucide-react";
import { isSupabaseConfigured, supabase } from "./lib/supabase";
import { cardSourceLabel, getCardLeadStats } from "./cardAnalytics";

type Status = "pending" | "approved" | "hold" | "rejected";
type Tab = "partner" | "pickup" | "advertising";
type TableName = "partner_applications" | "pickup_partner_applications" | "advertising_inquiries";
type Notice = { type: "ok" | "error"; text: string } | null;
type PartnerApplication = { id:string; store_name:string; owner_name:string; phone:string; address:string; business_type:string; inquiry:string|null; license_path:string; status?:Status; created_at:string; source_card?:string|null; source_staff?:string|null };
type PickupApplication = { id:string; store_name:string; owner_name:string; phone:string; address:string; pickup_hours:string|null; benefit_interest:string|null; status?:Status; created_at:string };
type AdvertisingInquiry = { id:string; company_name:string; contact_name:string; phone:string; category:string|null; budget:string|null; inquiry:string|null; status?:Status; created_at:string };
const ADMIN_EMAIL="psw3077@gmail.com";
const SQL_FILE_URL="https://github.com/psw3077/miso-bridge/blob/main/supabase/admin_setup.sql";
const GITHUB_REPO_URL="https://github.com/psw3077/miso-bridge";
const SUPABASE_SQL_URL="https://supabase.com/dashboard/project/uapndiopsckecpysdzuk/sql/new";
const SUPABASE_TABLE_URL="https://supabase.com/dashboard/project/uapndiopsckecpysdzuk/editor";
const CLOUDFLARE_URL="https://dash.cloudflare.com/";
export default function AdminDashboard(){
 const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[signedInEmail,setSignedInEmail]=useState<string|null>(null);const[partners,setPartners]=useState<PartnerApplication[]>([]);const[pickups,setPickups]=useState<PickupApplication[]>([]);const[ads,setAds]=useState<AdvertisingInquiry[]>([]);const[activeTab,setActiveTab]=useState<Tab>("partner");const[searchTerm,setSearchTerm]=useState("");const[notice,setNotice]=useState<Notice>(null);const[loading,setLoading]=useState(true);const[savingId,setSavingId]=useState<string|null>(null);
 useEffect(()=>{if(!supabase){setLoading(false);return;}supabase.auth.getSession().then(({data})=>{const e=data.session?.user.email??null;setSignedInEmail(e);if(e===ADMIN_EMAIL)void loadAll();else setLoading(false)});const{data:l}=supabase.auth.onAuthStateChange((_e,s)=>{const x=s?.user.email??null;setSignedInEmail(x);if(x===ADMIN_EMAIL)void loadAll();else{setPartners([]);setPickups([]);setAds([]);setLoading(false)}});return()=>l.subscription.unsubscribe()},[]);
 async function login(e:FormEvent){e.preventDefault();setNotice(null);if(!supabase)return setNotice({type:"error",text:"Supabase 연결이 필요합니다."});if(email.trim().toLowerCase()!==ADMIN_EMAIL)return setNotice({type:"error",text:"등록된 관리자 이메일만 로그인할 수 있습니다."});setLoading(true);const{error}=await supabase.auth.signInWithPassword({email:email.trim(),password});if(error){setLoading(false);setNotice({type:"error",text:error.message});return}setNotice({type:"ok",text:"관리자 로그인에 성공했습니다."})}
 async function logout(){if(supabase)await supabase.auth.signOut();setSignedInEmail(null);setPartners([]);setPickups([]);setAds([])}
 async function loadAll(){if(!supabase)return;setLoading(true);setNotice(null);const[p,u,a]=await Promise.all([supabase.from("partner_applications").select("*").order("created_at",{ascending:false}),supabase.from("pickup_partner_applications").select("*").order("created_at",{ascending:false}),supabase.from("advertising_inquiries").select("*").order("created_at",{ascending:false})]);const errors=[p.error,u.error,a.error].filter(Boolean);if(errors.length)setNotice({type:"error",text:`일부 목록 조회 실패: ${errors.map(x=>x?.message).join(" / ")}`});setPartners((p.data??[])as PartnerApplication[]);setPickups((u.data??[])as PickupApplication[]);setAds((a.data??[])as AdvertisingInquiry[]);setLoading(false)}
 async function openLicense(path:string){if(!supabase||!path)return;const{data,error}=await supabase.storage.from("business-licenses").createSignedUrl(path,300);if(error||!data?.signedUrl)return setNotice({type:"error",text:`사업자등록증 열기 실패: ${error?.message??"파일 없음"}`});window.open(data.signedUrl,"_blank","noopener,noreferrer")}
 async function changeStatus(table:TableName,id:string,status:Status){if(!supabase||savingId)return;setNotice(null);setSavingId(id);const{data,error}=await supabase.from(table).update({status}).eq("id",id).select("id, status").maybeSingle();if(error)setNotice({type:"error",text:`상태 변경 실패: ${error.message}`});else if(!data){setNotice({type:"error",text:"상태가 저장되지 않았습니다."});await loadAll()}else{if(table==="partner_applications")setPartners(x=>x.map(i=>i.id===id?{...i,status:data.status}:i));if(table==="pickup_partner_applications")setPickups(x=>x.map(i=>i.id===id?{...i,status:data.status}:i));if(table==="advertising_inquiries")setAds(x=>x.map(i=>i.id===id?{...i,status:data.status}:i));setNotice({type:"ok",text:"처리 상태가 저장되었습니다."})}setSavingId(null)}
 const statusSelect=(table:TableName,id:string,value?:Status)=><select disabled={savingId===id} value={value??"pending"} onChange={e=>changeStatus(table,id,e.target.value as Status)}><option value="pending">대기</option><option value="approved">승인</option><option value="hold">보류</option><option value="rejected">거절</option></select>;
 const q=searchTerm.trim().toLowerCase();const filteredPartners=useMemo(()=>partners.filter(x=>!q||[x.store_name,x.owner_name,x.phone,x.address,x.business_type,x.inquiry,x.source_card,x.source_staff].some(v=>String(v??"").toLowerCase().includes(q))),[partners,q]);const filteredPickups=useMemo(()=>pickups.filter(x=>!q||[x.store_name,x.owner_name,x.phone,x.address,x.pickup_hours,x.benefit_interest].some(v=>String(v??"").toLowerCase().includes(q))),[pickups,q]);const filteredAds=useMemo(()=>ads.filter(x=>!q||[x.company_name,x.contact_name,x.phone,x.category,x.budget,x.inquiry].some(v=>String(v??"").toLowerCase().includes(q))),[ads,q]);const cardStats=useMemo(()=>getCardLeadStats(partners),[partners]);const conversion=cardStats.total?Math.round(cardStats.approved/cardStats.total*100):0;const permissionSetupNeeded=!loading&&partners.length>0&&pickups.length===0&&ads.length===0;
 if(!isSupabaseConfigured)return <main className="admin-shell"><section className="admin-login"><ShieldCheck size={42}/><h1>미소브릿지 관리자</h1><p>Supabase 환경변수를 연결해 주세요.</p><a href="/">홈으로 돌아가기</a></section></main>;
 if(signedInEmail!==ADMIN_EMAIL)return <main className="admin-shell"><section className="admin-login"><ShieldCheck size={42}/><span>MISO BRIDGE ADMIN</span><h1>관리자 로그인</h1><p>관리자 이메일은 <b>{ADMIN_EMAIL}</b>입니다.</p><form onSubmit={login}><label>이메일<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>비밀번호<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{notice&&<div className={`admin-notice ${notice.type}`}>{notice.text}</div>}<button disabled={loading}><LogIn size={18}/>{loading?"로그인 중...":"로그인"}</button></form><a href="/">← 미소브릿지 홈</a></section></main>;
 return <main className="admin-page"><header className="admin-header"><div><span>MISO BRIDGE</span><h1>관리자 대시보드</h1></div><div className="admin-header-actions"><a className="admin-home-link" href="/"><Home size={17}/>홈페이지</a><button onClick={loadAll}><RefreshCw size={17}/>새로고침</button><button onClick={logout}><LogOut size={17}/>로그아웃</button></div></header>{notice&&<div className={`admin-notice admin-wide-notice ${notice.type}`}>{notice.text}</div>}
 <section className="admin-quick-tools"><div><span>QUICK TOOLS</span><h2>프로그램 바로가기</h2><p>관리 작업에 필요한 프로그램을 새 창으로 바로 엽니다.</p></div><nav><a href={SUPABASE_SQL_URL} target="_blank" rel="noreferrer"><Database/><b>Supabase SQL</b><small>권한 SQL 실행</small><ExternalLink/></a><a href={SUPABASE_TABLE_URL} target="_blank" rel="noreferrer"><TableProperties/><b>Supabase 데이터</b><small>접수 내역 확인</small><ExternalLink/></a><a href={GITHUB_REPO_URL} target="_blank" rel="noreferrer"><Code2/><b>GitHub</b><small>홈페이지 코드 관리</small><ExternalLink/></a><a href={CLOUDFLARE_URL} target="_blank" rel="noreferrer"><Cloud/><b>Cloudflare</b><small>배포 상태 확인</small><ExternalLink/></a></nav></section>
 {permissionSetupNeeded&&<section className="admin-permission-guide"><AlertTriangle size={28}/><div><b>일부 접수 건이 0으로 보이나요?</b><p>Supabase 관리자 조회 권한을 확인해 주세요.</p></div><a href={SQL_FILE_URL} target="_blank" rel="noreferrer"><Database size={17}/>권한 SQL 열기</a></section>}
 <section className="admin-stats"><article><Store/><div><b>{partners.length}</b><span>신규 거래 신청</span></div></article><article><MapPin/><div><b>{pickups.length}</b><span>픽업 파트너 신청</span></div></article><article><Megaphone/><div><b>{ads.length}</b><span>광고·입점 문의</span></div></article><article><Users/><div><b>{[...partners,...pickups,...ads].filter(x=>(x.status??"pending")==="pending").length}</b><span>전체 승인 대기</span></div></article></section>
 <section className="admin-stats"><article><CreditCard/><div><b>{cardStats.total}</b><span>MISO CARD 유입</span></div></article><article><ShieldCheck/><div><b>{cardStats.approved}</b><span>명함 유입 승인</span></div></article><article><Users/><div><b>{cardStats.pending}</b><span>명함 유입 대기</span></div></article><article><Store/><div><b>{conversion}%</b><span>명함 승인 전환율</span></div></article></section>
 {cardStats.byStaff.length>0&&<section className="admin-panel"><div className="admin-panel-title"><div><span>MISO CARD SALES</span><h2>전자명함 유입 순위</h2></div></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>순위</th><th>명함/담당자</th><th>신규거래 유입</th></tr></thead><tbody>{cardStats.byStaff.map((x,i)=><tr key={x.name}><td>{i+1}</td><td><strong>{x.name}</strong></td><td>{x.count}건</td></tr>)}</tbody></table></div></section>}
 <section className="admin-toolbar"><div className="admin-tabs"><button className={activeTab==="partner"?"active":""} onClick={()=>setActiveTab("partner")}>신규 거래 <b>{partners.length}</b></button><button className={activeTab==="pickup"?"active":""} onClick={()=>setActiveTab("pickup")}>픽업 파트너 <b>{pickups.length}</b></button><button className={activeTab==="advertising"?"active":""} onClick={()=>setActiveTab("advertising")}>광고·입점 <b>{ads.length}</b></button></div><label className="admin-search"><Search size={17}/><input value={searchTerm} onChange={e=>setSearchTerm(e.target.value)} placeholder="상호·대표자·전화·지역·명함 출처 검색"/></label></section>
 {activeTab==="partner"&&<section className="admin-panel"><div className="admin-panel-title"><div><span>PARTNER APPLICATIONS</span><h2>신규 거래 신청</h2></div></div>{loading?<p className="admin-empty">목록을 불러오는 중입니다.</p>:filteredPartners.length===0?<p className="admin-empty">검색 결과가 없습니다.</p>:<div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>접수일</th><th>매장/대표자</th><th>연락처·주소</th><th>업종</th><th>유입경로</th><th>사업자등록증</th><th>상태</th></tr></thead><tbody>{filteredPartners.map(item=><tr key={item.id}><td>{new Date(item.created_at).toLocaleString("ko-KR")}</td><td><strong>{item.store_name}</strong><small>{item.owner_name}</small></td><td><a href={`tel:${item.phone}`}><Phone size={14}/>{item.phone}</a><small>{item.address}</small></td><td>{item.business_type}</td><td><small>{cardSourceLabel(item)}</small></td><td>{item.license_path?<button className="document-button" onClick={()=>openLicense(item.license_path)}><FileText size={16}/>파일 보기</button>:"-"}</td><td>{statusSelect("partner_applications",item.id,item.status)}</td></tr>)}</tbody></table></div>}</section>}
 {activeTab==="pickup"&&<section className="admin-panel"><div className="admin-panel-title"><div><span>PICKUP PARTNERS</span><h2>픽업 파트너 신청</h2></div></div>{loading?<p className="admin-empty">목록을 불러오는 중입니다.</p>:filteredPickups.length===0?<p className="admin-empty">검색 결과가 없습니다.</p>:<div className="admin-table-wrap"><table className="admin-table"><tbody>{filteredPickups.map(item=><tr key={item.id}><td>{item.store_name}</td><td>{item.owner_name}</td><td>{item.phone}</td><td>{statusSelect("pickup_partner_applications",item.id,item.status)}</td></tr>)}</tbody></table></div>}</section>}
 {activeTab==="advertising"&&<section className="admin-panel"><div className="admin-panel-title"><div><span>ADVERTISING INQUIRIES</span><h2>광고·입점 문의</h2></div></div>{loading?<p className="admin-empty">목록을 불러오는 중입니다.</p>:filteredAds.length===0?<p className="admin-empty">검색 결과가 없습니다.</p>:<div className="admin-table-wrap"><table className="admin-table"><tbody>{filteredAds.map(item=><tr key={item.id}><td>{item.company_name}</td><td>{item.contact_name}</td><td>{item.phone}</td><td>{statusSelect("advertising_inquiries",item.id,item.status)}</td></tr>)}</tbody></table></div>}</section>}
 </main>;
}