import { FormEvent, useEffect, useMemo, useState } from "react";
import { Home, LogIn, LogOut, Phone, RefreshCw, Search, ShieldCheck, Store, Sparkles, Users } from "lucide-react";
import { isSupabaseConfigured, supabase } from "./lib/supabase";

type Status = "pending" | "contacted" | "quoted" | "approved" | "hold" | "rejected";
type Partner = { id:string; store_name:string; owner_name:string; phone:string; address:string; business_type:string; inquiry:string|null; status?:Status; created_at:string };
type Consulting = { id:string; name:string; phone:string; region:string; business_type:string; consulting_type?:string|null; opening_timing:string|null; budget:string|null; funding_needed:string|null; inquiry:string|null; status?:Status; created_at:string };
const ADMIN_EMAIL="psw3077@gmail.com";

export default function MisoAdmin(){
 const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [signed,setSigned]=useState<string|null>(null);
 const [partners,setPartners]=useState<Partner[]>([]); const [consulting,setConsulting]=useState<Consulting[]>([]); const [tab,setTab]=useState<"partner"|"consulting">("partner");
 const [q,setQ]=useState(""); const [loading,setLoading]=useState(true); const [notice,setNotice]=useState("");
 useEffect(()=>{ if(!supabase){setLoading(false);return;} supabase.auth.getSession().then(({data})=>{const e=data.session?.user.email??null;setSigned(e); if(e===ADMIN_EMAIL) void load(); else setLoading(false)}); const {data:l}=supabase.auth.onAuthStateChange((_e,s)=>{const e=s?.user.email??null;setSigned(e);if(e===ADMIN_EMAIL)void load();}); return()=>l.subscription.unsubscribe();},[]);
 async function login(e:FormEvent){e.preventDefault();if(!supabase)return;if(email.trim().toLowerCase()!==ADMIN_EMAIL){setNotice("등록된 관리자 이메일만 로그인할 수 있습니다.");return;}setLoading(true);const r=await supabase.auth.signInWithPassword({email:email.trim(),password});if(r.error){setNotice(r.error.message);setLoading(false);}}
 async function load(){if(!supabase)return;setLoading(true);const [p,c]=await Promise.all([supabase.from("partner_applications").select("*").order("created_at",{ascending:false}),supabase.from("consulting_inquiries").select("*").order("created_at",{ascending:false})]);setPartners((p.data??[]) as Partner[]);setConsulting((c.data??[]) as Consulting[]);if(p.error||c.error)setNotice([p.error?.message,c.error?.message].filter(Boolean).join(" / "));setLoading(false);}
 async function status(table:"partner_applications"|"consulting_inquiries",id:string,value:Status){if(!supabase)return;const r=await supabase.from(table).update({status:value}).eq("id",id);if(r.error)setNotice(r.error.message);else void load();}
 const term=q.trim().toLowerCase(); const fp=useMemo(()=>partners.filter(x=>!term||[x.store_name,x.owner_name,x.phone,x.address,x.business_type,x.inquiry].some(v=>String(v??"").toLowerCase().includes(term))),[partners,term]); const fc=useMemo(()=>consulting.filter(x=>!term||[x.name,x.phone,x.region,x.business_type,x.consulting_type,x.inquiry].some(v=>String(v??"").toLowerCase().includes(term))),[consulting,term]);
 const select=(table:"partner_applications"|"consulting_inquiries",id:string,v?:Status)=><select value={v??"pending"} onChange={e=>status(table,id,e.target.value as Status)}><option value="pending">접수</option><option value="contacted">상담중</option><option value="quoted">견적발송</option><option value="approved">완료</option><option value="hold">보류</option><option value="rejected">종료</option></select>;
 if(!isSupabaseConfigured)return <main className="admin-shell"><section className="admin-login"><ShieldCheck/><h1>MISO ONE 관리자</h1><p>Supabase 환경변수 연결이 필요합니다.</p><a href="/">홈으로</a></section></main>;
 if(signed!==ADMIN_EMAIL)return <main className="admin-shell"><section className="admin-login"><ShieldCheck/><span>MISO ONE CRM</span><h1>관리자 로그인</h1><form onSubmit={login}><label>이메일<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>비밀번호<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{notice&&<div className="admin-notice error">{notice}</div>}<button disabled={loading}><LogIn/>로그인</button></form><a href="/">← 홈페이지</a></section></main>;
 const pending=[...partners,...consulting].filter(x=>(x.status??"pending")==="pending").length;
 return <main className="admin-page"><header className="admin-header"><div><span>MISO ONE</span><h1>영업 CRM</h1></div><div className="admin-header-actions"><a className="admin-home-link" href="/"><Home/>홈페이지</a><button onClick={load}><RefreshCw/>새로고침</button><button onClick={()=>supabase?.auth.signOut()}><LogOut/>로그아웃</button></div></header>{notice&&<div className="admin-notice admin-wide-notice error">{notice}</div>}
 <section className="admin-stats"><article><Store/><div><b>{partners.length}</b><span>신규 거래</span></div></article><article><Sparkles/><div><b>{consulting.length}</b><span>통합 상담</span></div></article><article><Users/><div><b>{pending}</b><span>신규 접수</span></div></article><article><Phone/><div><b>{partners.length+consulting.length}</b><span>전체 영업 리드</span></div></article></section>
 <section className="admin-toolbar"><div className="admin-tabs"><button className={tab==="partner"?"active":""} onClick={()=>setTab("partner")}>신규 거래 <b>{partners.length}</b></button><button className={tab==="consulting"?"active":""} onClick={()=>setTab("consulting")}>통합 상담 <b>{consulting.length}</b></button></div><label className="admin-search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="상호·이름·전화번호·지역·상담유형 검색"/></label></section>
 {tab==="partner"?<section className="admin-panel"><div className="admin-panel-title"><div><span>NEW PARTNERS</span><h2>신규 거래 신청</h2></div></div>{loading?<p className="admin-empty">불러오는 중...</p>:<div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>접수일</th><th>상호/대표</th><th>연락처/지역</th><th>업종</th><th>문의</th><th>상태</th></tr></thead><tbody>{fp.map(x=><tr key={x.id}><td>{new Date(x.created_at).toLocaleString("ko-KR")}</td><td><strong>{x.store_name}</strong><small>{x.owner_name}</small></td><td><a href={`tel:${x.phone}`}><Phone/>{x.phone}</a><small>{x.address}</small></td><td>{x.business_type}</td><td><small style={{whiteSpace:"pre-wrap"}}>{x.inquiry}</small></td><td>{select("partner_applications",x.id,x.status)}</td></tr>)}</tbody></table></div>}</section>:
 <section className="admin-panel"><div className="admin-panel-title"><div><span>CONSULTING</span><h2>창업·자금·폐업·프랜차이즈 상담</h2></div></div>{loading?<p className="admin-empty">불러오는 중...</p>:<div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>접수일</th><th>상담유형/이름</th><th>연락처/지역</th><th>업종/시기</th><th>예산/자금</th><th>상태</th></tr></thead><tbody>{fc.map(x=><tr key={x.id}><td>{new Date(x.created_at).toLocaleString("ko-KR")}</td><td><strong>{x.consulting_type||"창업·자금"}</strong><small>{x.name}</small></td><td><a href={`tel:${x.phone}`}><Phone/>{x.phone}</a><small>{x.region}</small></td><td>{x.business_type}<small>{x.opening_timing}</small></td><td>{x.budget}<small>자금상담: {x.funding_needed}</small><small style={{whiteSpace:"pre-wrap"}}>{x.inquiry}</small></td><td>{select("consulting_inquiries",x.id,x.status)}</td></tr>)}</tbody></table></div>}</section>}</main>;
}
