create table if not exists public.partner_applications (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  owner_name text not null,
  phone text not null,
  store_name text not null,
  business_type text,
  address text not null,
  inquiry text,
  license_path text not null,
  status text not null default 'pending'
);

create table if not exists public.pickup_partner_applications (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  store_name text not null,
  owner_name text not null,
  phone text not null,
  address text not null,
  pickup_hours text,
  benefit_interest text,
  status text not null default 'pending'
);

create table if not exists public.advertising_inquiries (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  company_name text not null,
  contact_name text not null,
  phone text not null,
  category text,
  budget text,
  inquiry text,
  status text not null default 'new'
);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'business-licenses',
  'business-licenses',
  false,
  8388608,
  array['application/pdf','image/jpeg','image/png']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

alter table public.partner_applications enable row level security;
alter table public.pickup_partner_applications enable row level security;
alter table public.advertising_inquiries enable row level security;

drop policy if exists "public partner application insert" on public.partner_applications;
drop policy if exists "public pickup application insert" on public.pickup_partner_applications;
drop policy if exists "public advertising inquiry insert" on public.advertising_inquiries;
drop policy if exists "public business license upload" on storage.objects;

create policy "public partner application insert"
on public.partner_applications for insert to anon, authenticated
with check (status = 'pending');

create policy "public pickup application insert"
on public.pickup_partner_applications for insert to anon, authenticated
with check (status = 'pending');

create policy "public advertising inquiry insert"
on public.advertising_inquiries for insert to anon, authenticated
with check (status = 'new');

create policy "public business license upload"
on storage.objects for insert to anon, authenticated
with check (
  bucket_id = 'business-licenses'
  and (storage.foldername(name))[1] is not null
);
